name: spearbench
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - ffmpeg
  - libsndfile
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - tqdm
  - librosa
  - matplotlib
  - seaborn
  - spacy>=3.8,<3.9
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu118
      - torch==2.7.1+cu118
      - torchaudio==2.7.1+cu118
      - torchvision==0.22.1+cu118
      - transformers==4.46.3
      - soundfile
      - safetensors==0.7.0
      - sentence-transformers
      - huggingface-hub==0.36.2
      - tokenizers==0.20.3
      - openai
      - jiwer
      - silero-vad
      - praat-parselmouth
      - loralib
      - sentencepiece
      - einops
      - qwen-asr
      - websocket-client
      - https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl
